### ISSUE TITLE
Theme todo

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#40]
- [x] Neue Farben bei der anderen Umfrage.
- [ ] Der Bereich für den Titel auf der Titelfolie ist anscheinend die ganze Seite, das sieht bei Make ziemlich eng aus.
- [x] LaTeX-Inhaltsverzeichnis: war die vorher auch über die ganze Höhe verteilt auf der zweiten Seite?
- [x] Da kommen viele neue (wir hatten vorher keine) Warnungen über übervolle Vboxes. Woran liegt das? Was ist höher geworden?
- [x] Wenn ich mir LaTeX-Folie 44 angucke, denke ich, wir sollten die Doku-Buttons etwas kleiner machen, damit der dritte auch passt. Dann könnte man vielleicht auch den Titel-Balken etwas kleiner machen.
- [x] Wenn wir schon dabei sind, könnte man die weißen Ränder an den Seiten etwas schmaler machen.
- [x] Rote Überschriften (Befehle) sind schlecht lesbar, wahrscheinlich sollten wir die einfach weiß machen.
