### ISSUE TITLE
LaTeX Todo

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox-workshop#41]
- [x] Viele Codes und Ausgaben sind nicht mehr vertikal ausgerichtet. (Nicht schlimm, muss nur korrigiert werden)
- [x] Wir sollten versuchen, die Farben in den Listings an das Farbschema anzupassen.
- [x] Kriegen wir wirklich die Spezialzeichen-Befehle (`\\`, `\!`, …) nicht gefärbt?
- [x] Wenn wir Small-Caps zeigen (tun wir), sollten wir zeigen, wie man sie lädt. Die werden standardmäßig nicht gefunden.

**Comment by MaxNoe** [comment]
Bei mir werden die SmallCaps direkt gefunden:
```
\documentclass{scrartcl}

\usepackage{fontspec}


\begin{document}
\textsc{Hallo Welt}
\end{document}
```

Gibt:
![lm-smallcaps](https://cloud.githubusercontent.com/assets/5488440/9848891/9dddfed6-5ae5-11e5-879f-133f52bc0695.png)

**Comment by itoijala** [comment]
Stimmt.
Wenn man aber explizit `\setmainfont{Latin Modern Roman}` angibt, kriegt man sie nicht…

**Comment by itoijala** [comment]
Das wird in `texlive/2015/texmf-dist/tex/latex/euenc/eu*lmr.fd` definiert.

**Comment by MaxNoe** [comment]
Ah, ok. Das liegt daran, dass die SmallCaps normalerweise in der gleichen otf wie der Hauptfont eingebettet sind, bei Latin Modern sind die aber in einem eigenen File.

**Comment by MaxNoe** [comment]
Die Geschichte mit dem Syntax-Highlighting scheint nicht trivial lösbar zu sein:
http://tex.stackexchange.com/questions/267481/l

**Comment by kdungs** [comment]
Wie sieht es denn mit `minted` aus?

**Comment by MaxNoe** [comment]
Auf nochmal alles umbauen hätte ich keine Lust. Das wäre es mir nicht wert.
